/*
 * main.h
 *
 *  Created on: Sep 16, 2023
 *      Author: meisam
 */

#ifndef MAIN_H_
#define MAIN_H_

#define DUMMY_XPSR 0x00100000

#define MAX_TASKS 4

#define SIZE_TASK_STACK 1024U
#define SIZE_SCHEDULER_STACK 1024U

#define SRAM_START  0x20000000U
#define SRAM_SIZE (128 * 1024)
#define SRAM_END  (SRAM_START + SRAM_START)

#define TASK1_STACK_START SRAM_END
#define TASK2_STACK_START (SRAM_END - (1 * SIZE_TASK_STACK))
#define TASK3_STACK_START (SRAM_END - (2 * SIZE_TASK_STACK))
#define TASK4_STACK_START (SRAM_END - (3 * SIZE_TASK_STACK))

#define SCHEDULER_STACK_START (SRAM_END - (4 * SIZE_TASK_STACK))

#define TICK_HZ 1000U

#define HSI_CLOCK         		16000000U
#define SYSTICK_TIM_CLK   		HSI_CLOCK


#endif /* MAIN_H_ */
